image: docker:stable

options:
  docker: true

pipelines:
  default:
    - step:
        script:
          - ci/cidependencies.sh
          - docker-compose build
          - docker-compose up
          - docker-compose down
